name: Sync versioned formulas

on: [pull_request]

jobs:
  sync_versioned_formula:
    name: Sync current version of formula to a versioned formula
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Sync supergrain-cli
        shell: bash
        run: ./scripts/sync_versioned_formula.sh supergrain-cli
